# Generated by Django 5.0.6 on 2024-06-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slider',
            table='system_slider',
        ),
    ]
