# Generated by Django 5.0.6 on 2024-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_slider_desc_alter_slider_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(max_length=256, upload_to='%Y%m/slider', verbose_name='图片地址'),
        ),
    ]
